services:
  db:
    image: postgres:15.6
    restart: always
    container_name: db
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pattern_db
      POSTGRES_USER: pattern
      POSTGRES_PASSWORD: pattern
    ports:
      - '5432:5432'
    expose:
      - 5432
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
